<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '13.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'sg',
  'author' => 'Mike Andersen',
  'description' => 'Sugar Logging Aggregator',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'sugagator',
  'published_date' => '2024-11-19 16:50:39',
  'type' => 'module',
  'version' => 1732035040,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'sugagator',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'sg_LogsAggregator',
      'class' => 'sg_LogsAggregator',
      'path' => 'modules/sg_LogsAggregator/sg_LogsAggregator.php',
      'tab' => false,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/sg_LogsAggregator',
      'to' => 'modules/sg_LogsAggregator',
    ),
    1 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Include/sugagator.php',
      'to' => 'custom/Extension/application/Ext/Include/sugagator.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.sugagator.php',
      'to' => 'custom/Extension/application/Ext/Language/en_us.sugagator.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/custom/Extension/modules/sg_LogsAggregator/Ext/Vardefs/readonly_fields.php',
      'to' => 'custom/Extension/modules/sg_LogsAggregator/Ext/Vardefs/readonly_fields.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/custom/include/SugarLogger/SugarGator.php',
      'to' => 'custom/include/SugarLogger/SugarGator.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/custom/modules/sg_LogsAggregator/clients/base/filters/default/default.php',
      'to' => 'custom/modules/sg_LogsAggregator/clients/base/filters/default/default.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/custom/modules/sg_LogsAggregator/metadata/SearchFields.php',
      'to' => 'custom/modules/sg_LogsAggregator/metadata/SearchFields.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/custom/src/Logger/Handler/Factory/SugarGator.php',
      'to' => 'custom/src/Logger/Handler/Factory/SugarGator.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/custom/src/Logger/Handler/SugarGatorHandler.php',
      'to' => 'custom/src/Logger/Handler/SugarGatorHandler.php',
    ),
  ),
  'post_execute' => 
  array (
    0 => '<basepath>/scripts/post_install.php',
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);
